name: Build Wheels

on:
  push:
    branches: [main, Test-LiveView]
  pull_request:
    branches: [main, Test-LiveView]


jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x86_64, i686]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build and cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install build cibuildwheel

      - name: Build wheels
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.architecture }}
          CIBW_SKIP: "*-musllinux_*"
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: hardview-linux-wheels-${{ matrix.architecture }}
          path: wheelhouse/

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [AMD64, x86]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build and cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install build cibuildwheel

      - name: Build wheels
        env:
          CIBW_ARCHS_WINDOWS: ${{ matrix.architecture }}
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: hardview-windows-wheels-${{ matrix.architecture }}
          path: wheelhouse/
